language: python
python: 
  - "3.5"
cache: pip
sudo: false

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - "python manage.py makemigrations"
  - "python manage.py migrate"

script:
  - flake8 cmdbox
  - coverage run --source=pyprende setup.py test --settings=cmdbox.tests_settings

after_success:
  - coveralls