language: python
python: 
  - "3.5"
cache: pip
sudo: false

install:
  - pip install -r requirements.txt
  - pip install pytest-cov

before_script:
  - "python manage.py makemigrations"
  - "python manage.py migrate"

script:
  - py.test --cov=server

after_success:
  - coveralls