language: python
python: 
  - "3.5"
cache: pip
sudo: false

install:
  - pip install tox codecov

before_script:
  - "python manage.py makemigrations"
  - "python manage.py migrate"

script:
  - tox

after_success:
  - codecov 